name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t demo2:latest .

      - name: Run Docker container (local test)
        run: |
          docker run -d -p 8080:8080 --name demo2-test demo2:latest
          sleep 20
          docker logs demo2-test
          docker stop demo2-test